name: "pagely-deploy-staging"
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Deploy to Sugar Calendar - Staging
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run deploy
        uses: pagely/action-deploy@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs/wp-content/plugins/sc-custom-functions"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: "b2HAsg49wmx8tPopgiSyv5"
          PAGELY_APP_ID: "31779"
          PAGELY_WORKING_DIR: ${{github.workspace}}